import { readFileSync, writeFileSync } from 'node:fs';
import { pgGenerate } from 'drizzle-dbml-generator';
import * as schema from '../app/db/schema';

const OUT = './docs/db.dbml';

// Info yang tidak bisa diturunkan dari skema Drizzle: dipasang setelah generate.
const tableNotes: Record<string, string> = {
  regu: 'Regu ronda; tiap regu punya hari tetap per minggu',
  households: 'Rumah tangga (KK) - unit utama iuran, ronda, konsumsi, arisan',
  kas_transactions: 'Ledger kas RT. Tidak ada kolom saldo; saldo dihitung dari tabel ini',
  jimpitan_entries: 'Tidak ada baris = rumah tidak mengisi malam itu',
  jimpitan_periods: 'Rekap bulanan jimpitan; saat terkunci menghasilkan satu transaksi kas',
  konsumsi_turns: 'Terpisah dari ronda_nights (kunci tanggal sama) - rotasi independen',
  arisan_cycles: 'Arisan di luar kas RT (uang anggota, bukan uang RT)'
};

// "tabel.kolom" -> catatan kolom
const columnNotes: Record<string, string> = {
  'regu.hari': '0 = Minggu .. 6 = Sabtu',
  'kas_transactions.sumber_tipe': "'sampah_bill' | 'jimpitan_period' | null (manual). Polymorphic - tanpa FK",
  'kas_transactions.sumber_id': 'id baris di tabel sumber_tipe. Polymorphic - tanpa FK',
  'sampah_bills.periode': 'selalu tanggal 1 bulan tsb',
  'jimpitan_periods.periode': 'tanggal 1 bulan tsb',
  'ronda_attendance.pengganti_household_id': 'rumah pengganti bila status = diganti'
};

// nama index -> catatan (partial index tidak terwakili di DBML)
const indexNotes: Record<string, string> = {
  kas_sumber_unik: 'where sumber_tipe is not null - satu sumber = satu transaksi kas',
  arisan_pemenang_sekali_unik:
    'where pemenang_member_id is not null - satu anggota menang sekali per siklus'
};

const groups: Record<string, string[]> = {
  identitas: ['regu', 'households', 'users'],
  kas: ['kas_transactions', 'sampah_bills', 'jimpitan_entries', 'jimpitan_periods'],
  ronda_konsumsi: ['ronda_nights', 'ronda_attendance', 'konsumsi_turns'],
  arisan: ['arisan_cycles', 'arisan_members', 'arisan_periods', 'arisan_payments'],
  lainnya: ['pengumuman']
};

const esc = (s: string) => s.replace(/'/g, "\\'");
const addNote = (attrs: string, note: string) =>
  attrs.replace(/\]$/, `, note: '${esc(note)}']`);

pgGenerate({ schema, out: OUT, relational: false });

let table = '';
const lines = readFileSync(OUT, 'utf8')
  .split('\n')
  .map((line) => {
    const t = line.match(/^table (\w+) \{$/);
    if (t) table = t[1];

    const col = line.match(/^(\s{2}(\w+) \S+)( \[.*\])?$/);
    if (col) {
      const note = columnNotes[`${table}.${col[2]}`];
      if (note) return col[1] + (col[3] ? addNote(col[3], note) : ` [note: '${esc(note)}']`);
    }

    const idx = line.match(/^(\s+\(.*\) )(\[name: '(\w+)'.*\])$/);
    if (idx && indexNotes[idx[3]]) return idx[1] + addNote(idx[2], indexNotes[idx[3]]);

    return line;
  });

// Note: tabel disisipkan sebelum kurung tutup tabel.
const withNotes: string[] = [];
table = '';
for (const line of lines) {
  const t = line.match(/^table (\w+) \{$/);
  if (t) table = t[1];
  if (line === '}' && table) {
    if (tableNotes[table]) withNotes.push('', `  Note: '${esc(tableNotes[table])}'`);
    table = '';
  }
  withNotes.push(line);
}

const grouped = Object.values(groups).flat();
const orphan = grouped.filter((n) => !withNotes.includes(`table ${n} {`));
if (orphan.length) throw new Error(`Group refers to unknown table(s): ${orphan.join(', ')}`);
const ungrouped = withNotes
  .map((l) => l.match(/^table (\w+) \{$/)?.[1])
  .filter((n): n is string => !!n && !grouped.includes(n));
if (ungrouped.length)
  throw new Error(`Add to groups in scripts/gen-dbml.ts: ${ungrouped.join(', ')}`);

const groupBlocks = Object.entries(groups).map(
  ([name, tables]) => `TableGroup ${name} {\n${tables.map((t) => `  ${t}`).join('\n')}\n}`
);

writeFileSync(
  OUT,
  [
    '// GENERATED by `npm run db:dbml` from app/db/schema.ts - jangan edit manual.',
    '// Catatan, grup, dan anotasi tambahan ada di scripts/gen-dbml.ts.',
    '',
    withNotes.join('\n').trimEnd(),
    '',
    ...groupBlocks.flatMap((b) => [b, ''])
  ].join('\n')
);
